language: python
sudo: false

addons:
  apt_packages:
      - pandoc
env:
  global:
    - python: 3.5
    - BUILD_DOCS: true
    - GH_REF: github.com/ericdill/ericdill.github.io
    - secure: "Z9sFg0cXkS18bQqSghPGkWTOi9p7UD7wWhj5KRjBDnqwfJBTEewy8s/hCRX7hbZEi4+ViDYKxdTZbjl1dXpBtw/ALAqGAy0V97NeyBZ0yeyWp9I4UjVeHci3yTmSOws6aViIeTv6dU0uN+zxHsTVB5bQPH+CgXsOyB1wR+jKdck="
before_install:
  # clone conda install/build/upload helper scripts and make them executable
  - git clone https://github.com/NSLS-II/nsls2-ci ~/scripts
  - chmod +x ~/scripts/*.sh
  - . ~/scripts/install-miniconda.sh



install:
  - export GIT_FULL_HASH=`git rev-parse HEAD`
  - conda config --set always_yes true
  - conda update conda
  - conda install sphinx numpydoc pip jsonschema ipython matplotlib
  - pip install sphinx_bootstrap_theme sphinxcontrib-napoleon

script:
  - chmod +x build_docs.sh
  - ./build_docs.sh

after_success:
  - if [ $TRAVIS_BRANCH == 'auto-build' ] && [ $TRAVIS_PULL_REQUEST == 'false' ]; then
      base=`basename $TRAVIS_REPO_SLUG`
      # prepend base with 'docs/' if it is not the parent repo
      if [ $base != 'docs' ]; then
        base="docs/$base";
      fi;
      echo "cloning to /tmp/$base"
      # inside this git repo we'll pretend to be a new user
      git config --global user.name "Travis CI"
      git config --global user.email "travis@nomail"
      # clone the existing github url to some directory
      git clone https://github.com/NSLS-II/NSLS-II.github.io /tmp/$base
      cp -rv build/html/* /tmp/$base
      cd /tmp/$base
      git add -A
      git commit -m "Autogenerated pages `date`"
      # Force push from the current repo's master branch to the remote
      # repo's gh-pages branch. (All previous history on the gh-pages branch
      # will be lost, since we are overwriting it.) We redirect any output to
      # /dev/null to hide any sensitive credential data that might otherwise be exposed.
      git push "https://${GH_TOKEN}@${GH_REF}" master > /dev/null 2>&1
    fi;
  - env
