language : python
python:
  - 3.6
sudo: false
env:
  global:
    - secure: "Y6tBB5CwAxaHPxLzwyyoQKXEwLK68ni8GqzoaYCYbrjLhSFqEDCk6Si7UPmMoED8t7hyxFZofPfEpmOLBoronWUQycnB/K/oxYFfKyEXxNxGpY/iaQk/XCC6rkJ3g863QKdAsgobBgJIClDczZ7leY3RlN+mHfH0wohCBLFAh0E="
addons:
  apt:
    sources:
      # https://apt.repos.intel.com/setup/intelproducts.list
      - sourceline: deb https://apt.repos.intel.com/intelpython binary/
        key_url: https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS-2019.PUB
      - sourceline: deb https://apt.repos.intel.com/mkl all main
        key_url: https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS-2019.PUB
      - sourceline: deb https://apt.repos.intel.com/ipp all main
        key_url: https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS-2019.PUB
      - sourceline: deb https://apt.repos.intel.com/tbb all main
        key_url: https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS-2019.PUB
      - sourceline: deb https://apt.repos.intel.com/daal all main
        key_url: https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS-2019.PUB
      - sourceline: deb https://apt.repos.intel.com/mpi all main
        key_url: https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS-2019.PUB
    packages:
      - intel-mkl-2018.2-046  # needed for tomopy

install:
  - pip install -q -r requirements.txt
  - pip install scikit-build  # build dep for tomopy 
  - pip install git+https://github.com/tomopy/tomopy
  - ls -alF /home/travis/virtualenv/python3.6.3/lib/
  - export LD_LIBRARY_PATH="/home/travis/virtualenv/python3.6.3/lib/":$LD_LIBRARY_PATH

script:
  - set -e
  - make html
  - doctr deploy --deploy-repo NSLS-II/NSLS-II.github.io --deploy-branch-name master .
